import './globals.css'
import Script from 'next/script'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Script src="https://js.braintreegateway.com/web/dropin/1.31.0/js/dropin.min.js"/>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
